### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by BlueDasher334** [MobilePorting/LeatherEngine-LTS-Mobile#1]
when i add mods it have some bugs

**Comment by moxie-coder** [comment]
what kind of bugs exactly? can you be more specific?

**Comment by BlueDasher334** [comment]
when i add a mod, sometimes doesnt detect the sprites, songs and charts when it have it

**Comment by mcagabe19** [comment]
well shrug, idk about leather engine goto le server
